version: "3.9"

services:
  redis:
    image: redis:7
    container_name: notification-redis
    volumes:
      - redis-data:/data
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--save", "900", "1",
        "--save", "300", "10",
        "--save", "60", "10000"
      ]
    restart: unless-stopped
    networks:
      - shared-backend-net

  backend:
    build: .
    container_name: notification-backend
    ports:
      - "4000:4000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # ðŸ”¥ ADD THIS
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - shared-backend-net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:5540"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - shared-backend-net

volumes:
  redis-data:

networks:
  shared-backend-net:
    external: true
